config/routes.rb
Kaohon::Application.routes.draw do
  resources :posts

  resources :users do
    member do
      get :friends
    end
  end

  resources :friendships
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/me', to: 'users#show', via: 'get'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :friender, class_name: "User"
	belongs_to :friended, class_name: "User"
	validates :friender_id, presence: true
	validates :friended_id, presence: true
	
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :create_remember_token
	
	has_secure_password
	has_many :posts, dependent: :destroy
	has_many :friendships, foreign_key: "friender_id", dependent: :destroy 
	has_many :friends, through: :friendships, source: :friended



	

	validates :name, presence: true
	validates :username, presence: true
	validates :password, presence: true
	validates :password_confirmation, presence: true

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.digest(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end

  	def friend(friended_user)
  		unless friends?(friended_user)
	  		self.friendships.create(friended_id: friended_user.id)
	  		friended_user.friendships.create(friended_id: self.id)
	  	end
  		# friendships.create(friender_id: friended_user.id, friended_id: self.id)
  	end

  	def friends?(friended_user)
  		self.friendships.find_by_friended_id(friended_user.id)
  	end

  	def unfriend(friended_user)
  		self.friendships.find_by_friended_id(friended_user.id).destroy
  		friended_user.friendships.find_by_friended_id(self.id).destroy
  	end

  	

  	private
  		def create_remember_token
      		self.remember_token = User.digest(User.new_remember_token)
    	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper :all
  helper_method :current_user_session, :current_user
  include SessionsHelper

  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def create
		@friended_user = User.find(params[:friendship][:friended_id])
		current_user.friend(@friended_user)
		# @friended_user.friend(current_user)
		redirect_to @friended_user
	end

	def destroy
		@unfriended_user = User.find(params[:friendship][:friended_id])
		current_user.unfriend(@unfriended_user)
		redirect_to @unfriended_user
	end



	private
		def friendship_params
		  params.require(:friendship).permit(:friender_id, :friended_id)
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@post = current_user.posts.build if signed_in?
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :signed_in_user
  before_filter :correct_user, only: :destroy

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  # def new
  #   @post = Post.new
  # end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_url, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
        
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		user = User.find_by(username: params[:session][:username])
		if user && user.authenticate(params[:session][:password])
			# sign user in...redirect to user.show
			sign_in user
			redirect_to root_path
		else
			flash.now[:error] = 'invalid!'
			render 'new'
		end


	end


	def destroy
		sign_out
		redirect_to signin_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    
    @posts = @user.posts.order("created_at DESC")
    @post = current_user.posts.build if signed_in?
  end


  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        flash[:success] = "Signed up! You're now logged in."

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
        
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def friends
      @user = User.find(params[:id])
      @friends = @user.friends
      render 'friends'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :name)
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)

		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end
	def signed_in_user
	  unless signed_in?
	    store_location
	    redirect_to signin_url, notice: "Please sign in."
	  end
	end
	def signed_in?
		!current_user.nil?
	end

	def sign_out
		current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    	cookies.delete(:remember_token)
		self.current_user = nil
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
    	user == current_user
  	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<!-- <a class="brand" href="#">Title</a> -->
			<nav>
				<ul class="nav navbar-nav">
					
					<!-- <li><a href="#">Link</a></li> -->
					
					
					

						<li><%= link_to "Feed", root_path %> </li>
						<li><%= link_to "User Directory", users_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Profile", current_user %></li>
						
						
						<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
						<li><%= link_to "Welcome, " + current_user.name + " (" + current_user.username + ")", current_user %></li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_new_post_form.html.erb
<% form_for(@post), :html => {:class => "form-group"}) do |f| %>
	<div class="field">
	  <%= f.label :content %><br>
	  <%= f.text_area :content, placeholder: "Write your post!" %>
	</div>
	
	<div class="actions">
	  <%= f.submit %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kaohon</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>


</body>
</html>

app/views/pages/_post_form.html.erb
<%= form_for(@post, :html => {:class => "form-group"}) do |f| %>
	<div class="field">
	  <%= f.label :content %><br>
	  <%= f.text_area :content, placeholder: "Write your post!" %>
	</div>
	
	<div class="actions">
	  <%= f.submit "Submit your post!", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/pages/home.html.erb
<% if signed_in? %>
	<h1>Welcome to Kaohon!</h1>
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Username:</strong>
	  <%= current_user.username %>
	</p>

	<p>
	  <strong>Name:</strong>
	  <%= current_user.name %>
	</p>
	<p><%= render 'pages/post_form' %></p>
	
	<div class="posts">
		<strong>Friends' posts</strong>
		<%= render 'users/feed' %>
	</div>

	<%= link_to 'Edit', edit_user_path(current_user) %> |
	<%= link_to 'Back', users_path %>
<% else %>
<div class="jumbotron">
	<h1>Welcome to Kaohon!</h1>
	<p>Please sign in.</p>
		<%= link_to "Sign up!", signup_path,
	                                class: "btn btn-lg btn-primary", role: "button" %>
		<%= link_to "Sign in!", signin_path,
	                                class: "btn btn-lg btn-primary", role: "button" %>
</div>

<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
			<%= post.user.name %>
		</h3>
		<%= post.created_at %>
	</div>
	<div class="panel-body">
		<%= post.content %>
	</div>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_feed.html.erb
<% Post.all.order("created_at DESC").each do |post| %>
	<% if current_user.friends?(User.find(post.user_id)) %>
		<%= render post %>
	<% end %>
<% end %>
	

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:class => "form-group"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Finish!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/friends.html.erb
<h2><%= @friends.count %> friends</h2>

<li class="friends">
<% @friends.each do |friend| %>
	<li class="friend"><%= link_to friend.name, friend %></li>
<% end %>
</li>

app/views/users/index.html.erb
<h1>User Directory</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.name %></td>

        
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Sign up for Kaohon!</h1>

<%= render 'form' %>



<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Friends:</strong>
  <%= @user.friendships.count %>
</p>


<% if signed_in? %>
	<% if current_user?(@user) %>
		<%= render 'pages/post_form' %>
	<% end %>
	<% unless current_user?(@user) %>
		
		<% if !current_user.friends?(@user) %>
			<%= form_for(current_user.friendships.build(friended_id: @user.id)) do |f| %>
				<%= f.hidden_field :friended_id %>
				<%= f.submit "Friend!", class: "btn btn-primary" %>
			<% end %>
		<% else %>
			<%= form_for(current_user.friendships.find_by_friended_id(@user.id), html: { method: :delete }) do |f| %>
				<%= f.hidden_field :friended_id %>
				<%= f.submit "Unfriend!", class: "btn btn-danger" %>
			<% end %>

		<% end %>
	<% end %>
<% end %>
<br /> 

<div class="posts">
	<%= render @posts %>
</div>

<% if current_user?(@user) %>
	<%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', users_path %>